spring:
  application:
    name: orderHub_project

  datasource:
    url: jdbc:postgresql://localhost:5435/orderhub_db
    username: orderhub_user
    password: postgres
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#  flyway:
#    user: orderhub_user
#    password: postgres
#    enabled: false
#    locations: classpath:db/migration

  liquibase:
    user: orderhub_user
    password: postgres
    enabled: true
    change-log: classpath:db/changelog/changelog_master.yaml


server:
  port: 8084

logging:
  level:
    org.hibernate.sql: DEBUG


